#!/usr/bin/env bash
#PBS -N example
#PBS -q gpu
#PBS -l select=1:gpuname=hopper:ngpus=1:ncpus=1:mpiprocs=1:mem=8000mb
#PBS -l walltime=1:00:00
#PBS -j oe
#PBS -o example.qsub_out

# change into submission directory
cd $PBS_O_WORKDIR

# list NVIDIA cards, make clean, load the cuda module, make, and run main
lspci -vvv | grep "NVIDIA" && \
  make clean && \
  module load cuda && \
  make main && \
  ./main
